In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import datetime
import numpy as np
%matplotlib inline

In [6]:
pov_stats_csv = pd.read_csv('../data/Using/PovStatsData.csv')
pov_stats_csv.head(25)

,Country Name,Country Code,Indicator Name,Indicator Code,1974,1975,1976,1977,1978,1979,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,Unnamed: 49
0,East Asia & Pacific,EAS,Annualized growth in per capita real survey me...,SI.SPR.PC40.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,East Asia & Pacific,EAS,Annualized growth in per capita real survey me...,SI.SPR.PT10.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,East Asia & Pacific,EAS,Annualized growth in per capita real survey me...,SI.SPR.PT60.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,East Asia & Pacific,EAS,Annualized growth in per capita real survey me...,SI.SPR.PCAP.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,East Asia & Pacific,EAS,Annualized growth in per capita real survey me...,SI.POV.XPND.MD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,East Asia & Pacific,EAS,Gini index (World Bank estimate),SI.POV.GINI,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,East Asia & Pacific,EAS,Income share held by fourth 20%,SI.DST.04TH.20,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,East Asia & Pacific,EAS,Income share held by highest 10%,SI.DST.10TH.10,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,East Asia & Pacific,EAS,Income share held by highest 20%,SI.DST.05TH.20,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,East Asia & Pacific,EAS,Income share held by lowest 10%,SI.DST.FRST.10,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,East Asia & Pacific,EAS,Income share held by lowest 20%,SI.DST.FRST.20,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,East Asia & Pacific,EAS,Income share held by second 20%,SI.DST.02ND.20,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,East Asia & Pacific,EAS,Income share held by third 20%,SI.DST.03RD.20,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,East Asia & Pacific,EAS,Median daily per capita income or consumption ...,SI.POV.XPND.MD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,East Asia & Pacific,EAS,"Multidimensional poverty, Drinking water (% of...",SI.POV.WATR.MI,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,East Asia & Pacific,EAS,"Multidimensional poverty, Educational attainme...",SI.POV.ATTM.MI,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,East Asia & Pacific,EAS,"Multidimensional poverty, Educational enrollme...",SI.POV.ENRL.MI,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,East Asia & Pacific,EAS,"Multidimensional poverty, Electricity (% of po...",SI.POV.ELEC.MI,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,East Asia & Pacific,EAS,"Multidimensional poverty, Headcount ratio (% o...",SI.POV.HCRT.MI,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,East Asia & Pacific,EAS,"Multidimensional poverty, Monetary poverty (% ...",SI.POV.DDAY.MI,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,East Asia & Pacific,EAS,"Multidimensional poverty, Sanitation (% of pop...",SI.POV.SANI.MI,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,East Asia & Pacific,EAS,Number of poor at $1.90 a day (2011 PPP) (mill...,SI.POV.NOP1,NaN,NaN,NaN,NaN,NaN,NaN,...,2.121000e+02,1.616000e+02,1.373000e+02,6.600000e+01,5.380000e+01,4.210000e+01,3.540000e+01,2.920000e+01,2.460000e+01,NaN
22,East Asia & Pacific,EAS,Number of poor at $3.20 a day (2011 PPP) (mill...,SI.POV.LMIC.NO,NaN,NaN,NaN,NaN,NaN,NaN,...,5.894000e+02,5.126000e+02,4.614000e+02,3.404000e+02,2.933000e+02,2.428000e+02,2.114000e+02,1.743000e+02,1.476000e+02,NaN
23,East Asia & Pacific,EAS,Number of poor at $5.50 a day (2011 PPP) (mill...,SI.POV.UMIC.NO,NaN,NaN,NaN,NaN,NaN,NaN,...,1.093800e+03,1.027400e+03,9.607000e+02,8.429000e+02,7.689000e+02,6.987000e+02,6.408000e+02,5.712000e+02,5.138000e+02,NaN
24,East Asia & Pacific,EAS,"Population, total",SP.POP.TOTL,1.416257e+09,1.443359e+09,1.467569e+09,1.490449e+09,1.513227e+09,1.536435e+09,...,2.206885e+09,2.221673e+09,2.236819e+09,2.252047e+09,2.267482e+09,2.282856e+09,2.298486e+09,2.314098e+09,2.328138e+09,NaN

In [5]:
pov_stats_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10730 entries, 0 to 10729
Data columns (total 50 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    10730 non-null  object
 1   Country Code    10730 non-null  object
 2   Indicator Name  10730 non-null  object
 3   Indicator Code  10730 non-null  object
 4   1974            217 non-null    float64
 5   1975            217 non-null    float64
 6   1976            183 non-null    float64
 7   1977            192 non-null    float64
 8   1978            200 non-null    float64
 9   1979            268 non-null    float64
 10  1980            234 non-null    float64
 11  1981            374 non-null    float64
 12  1982            280 non-null    float64
 13  1983            314 non-null    float64
 14  1984            342 non-null    float64
 15  1985            446 non-null    float64
 16  1986            494 non-null    float64
 17  1987            607 non-null    float64
 18  1988            411 non-null    float64
 19  1989            509 non-null    float64
 20  1990            589 non-null    float64
 21  1991            622 non-null    float64
 22  1992            854 non-null    float64
 23  1993            674 non-null    float64
 24  1994            740 non-null    float64
 25  1995            947 non-null    float64
 26  1996            872 non-null    float64
 27  1997            759 non-null    float64
 28  1998            934 non-null    float64
 29  1999            838 non-null    float64
 30  2000            1197 non-null   float64
 31  2001            953 non-null    float64
 32  2002            1282 non-null   float64
 33  2003            1377 non-null   float64
 34  2004            1594 non-null   float64
 35  2005            1741 non-null   float64
 36  2006            1716 non-null   float64
 37  2007            1611 non-null   float64
 38  2008            1701 non-null   float64
 39  2009            1807 non-null   float64
 40  2010            1950 non-null   float64
 41  2011            1890 non-null   float64
 42  2012            2058 non-null   float64
 43  2013            2003 non-null   float64
 44  2014            2160 non-null   float64
 45  2015            2155 non-null   float64
 46  2016            2185 non-null   float64
 47  2017            2140 non-null   float64
 48  2018            2504 non-null   float64
 49  Unnamed: 49     0 non-null      float64
dtypes: float64(46), object(4)
memory usage: 4.1+ MB

In [7]:
pov_stats_rename = pov_stats_csv.rename(columns = {'Country Name': 'Country', 'Country Code': 'Code',})
pov_stats_rename.head()

,Country,Code,Indicator Name,Indicator Code,1974,1975,1976,1977,1978,1979,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,Unnamed: 49
0,East Asia & Pacific,EAS,Annualized growth in per capita real survey me...,SI.SPR.PC40.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,East Asia & Pacific,EAS,Annualized growth in per capita real survey me...,SI.SPR.PT10.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,East Asia & Pacific,EAS,Annualized growth in per capita real survey me...,SI.SPR.PT60.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,East Asia & Pacific,EAS,Annualized growth in per capita real survey me...,SI.SPR.PCAP.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,East Asia & Pacific,EAS,Annualized growth in per capita real survey me...,SI.POV.XPND.MD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
pov_stats_rename.isna().sum()

Country               0
Code                  0
Indicator Name        0
Indicator Code        0
1974              10513
1975              10513
1976              10547
1977              10538
1978              10530
1979              10462
1980              10496
1981              10356
1982              10450
1983              10416
1984              10388
1985              10284
1986              10236
1987              10123
1988              10319
1989              10221
1990              10141
1991              10108
1992               9876
1993              10056
1994               9990
1995               9783
1996               9858
1997               9971
1998               9796
1999               9892
2000               9533
2001               9777
2002               9448
2003               9353
2004               9136
2005               8989
2006               9014
2007               9119
2008               9029
2009               8923
2010               8780
2011               8840
2012               8672
2013               8727
2014               8570
2015               8575
2016               8545
2017               8590
2018               8226
Unnamed: 49       10730
dtype: int64

In [9]:
pov_stats_rename.shape

(10730, 50)

In [15]:
pov_stats_clean['Indicator Code'].value_counts()

SI.POV.RUGP.NC       185
SI.POV.DDAY.65       185
SI.POV.URGP.NC       185
SI.DST.04TH.20       185
SI.SPR.PT60          185
SI.POV.NAHC          185
SI.SPR.PT10.ZG       185
SI.POV.DDAY.RU       185
SI.DST.03RD.20       185
SI.POV.GINI          185
SI.POV.ELEC.MI       185
SI.POV.DDAY.UR       185
SI.POV.URHC.NC       185
SI.DST.FRST.10       185
SI.SPR.PT60.ZG       185
SI.SPR.PC40.ZG       185
SI.POV.DDAY.16.PL    185
SI.POV.RUHC          185
SI.POV.NOP1          185
SI.POV.DDAY.16.SG    185
SI.POV.DDAY.FE       185
SI.DST.FRST.20       185
SI.POV.UMIC.GP       185
SI.SPR.PCAP          185
SI.POV.DDAY.MI       185
SI.POV.DDAY.MA       185
SI.SPR.PC40          185
SI.DST.10TH.10       185
SI.POV.UMIC.NO       185
SI.POV.NAGP.NC       185
SI.POV.DDAY          185
SI.POV.LMIC.GP       185
SI.DST.02ND.20       185
SI.POV.UMIC          185
SI.POV.DDAY.16.PR    185
SI.POV.DDAY.16.ST    185
SI.POV.LMIC          185
SI.POV.URGP          185
SI.POV.HCRT.MI       185
SI.POV.RUHC.NC       185
SI.POV.DDAY.1564     185
SI.DST.05TH.20       185
SI.POV.NAHC.NC       185
SI.POV.XPND.MD.ZG    185
SI.POV.DDAY.14       185
SI.POV.WATR.MI       185
SI.POV.GAPS          185
SP.POP.TOTL          185
SI.SPR.PT10          185
SI.POV.XPND.MD       185
SI.POV.URHC          185
SI.POV.ATTM.MI       185
SI.SPR.PCAP.ZG       185
SI.POV.SANI.MI       185
SI.POV.NAGP          185
SI.POV.LMIC.NO       185
SI.POV.ENRL.MI       185
SI.POV.RUGP          185
Name: Indicator Code, dtype: int64

In [16]:
pov_stats_clean = pov_stats_rename.drop(columns = ['Unnamed: 49', 'Indicator Code'])
pov_stats_clean.head()

,Country,Code,Indicator Name,1974,1975,1976,1977,1978,1979,1980,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,East Asia & Pacific,EAS,Annualized growth in per capita real survey me...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,East Asia & Pacific,EAS,Annualized growth in per capita real survey me...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,East Asia & Pacific,EAS,Annualized growth in per capita real survey me...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,East Asia & Pacific,EAS,Annualized growth in per capita real survey me...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,East Asia & Pacific,EAS,Annualized growth in per capita real survey me...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
pov_stats_clean['Country'].value_counts()

Georgia                58
Gambia, The            58
East Asia & Pacific    58
Lithuania              58
Botswana               58
                       ..
Seychelles             58
Gabon                  58
Korea, Rep.            58
Guinea                 58
Norway                 58
Name: Country, Length: 185, dtype: int64

In [18]:
pov_stats_clean['Indicator Name'].value_counts()

Multidimensional poverty, Drinking water (% of population deprived)                                                                                            185
Poverty headcount ratio at national poverty lines (% of population)                                                                                            185
Poverty headcount ratio at $1.90 a day, with primary education (2011 PPP) (% of population age 16+ with primary education)                                     185
Median daily per capita income or consumption expenditure (2011 PPP)                                                                                           185
Poverty headcount ratio at $1.90 a day, without education (2011 PPP) (% of population age 16+ without education)                                               185
Income share held by highest 20%                                                                                                                               185
Annualized growth in per capita real survey mean consumption or income, top 60% (%)                                                                            185
Income share held by highest 10%                                                                                                                               185
Poverty headcount ratio at $1.90 a day, urban (2011 PPP) (% of urban population)                                                                               185
Poverty headcount ratio at $1.90 a day, Male  (2011 PPP) (% of male population)                                                                                185
Population, total                                                                                                                                              185
Annualized growth in per capita real survey median income or consumption expenditure (%)                                                                       185
Poverty gap at national poverty lines (%)                                                                                                                      185
Number of poor at $3.20 a day (2011 PPP) (millions)                                                                                                            185
Poverty headcount ratio at national poverty lines (% of population), including noncomparable values                                                            185
Income share held by lowest 10%                                                                                                                                185
Rural poverty gap at national poverty lines (%), including noncomparable values                                                                                185
Poverty gap at national poverty lines (%), including noncomparable values                                                                                      185
Multidimensional poverty, Headcount ratio (% of population)                                                                                                    185
Annualized growth in per capita real survey mean consumption or income, top 10% (%)                                                                            185
Survey mean consumption or income per capita, total population (2011 PPP $ per day)                                                                            185
Annualized growth in per capita real survey mean consumption or income, bottom 40% (%)                                                                         185
Annualized growth in per capita real survey mean consumption or income, total population (%)                                                                   185
Income share held by third 20%                                                                                                                                 185
Poverty headcount ratio at $1.90 a day, age 0-14  (2011 PPP) (% of population age 0-14)                                                                        185
Multidimensional poverty, Monetary poverty (% of population deprived)                                                                                          185
Poverty headcount ratio at $1.90 a day, Female (2011 PPP) (% of female population)                                                                             185
Poverty headcount ratio at $3.20 a day (2011 PPP) (% of population)                                                                                            185
Poverty headcount ratio at $1.90 a day (2011 PPP) (% of population)                                                                                            185
Gini index (World Bank estimate)                                                                                                                               185
Poverty headcount ratio at $1.90 a day,  with Tertiary/post-secondary education (2011 PPP) (% of population age 16+ with Tertiary/post-secondary education)    185
Number of poor at $1.90 a day (2011 PPP) (millions)                                                                                                            185
Multidimensional poverty, Educational enrollment (% of population deprived)                                                                                    185
Poverty headcount ratio at $1.90 a day, age 15-64 (2011 PPP) (% of population age 15-64)                                                                       185
Poverty gap at $1.90 a day (2011 PPP) (%)                                                                                                                      185
Multidimensional poverty, Electricity (% of population deprived)                                                                                               185
Multidimensional poverty, Educational attainment (% of population deprived)                                                                                    185
Rural poverty gap at national poverty lines (%)                                                                                                                185
Survey mean consumption or income per capita, bottom 40% (2011 PPP $ per day)                                                                                  185
Poverty headcount ratio at $5.50 a day (2011 PPP) (% of population)                                                                                            185
Urban poverty headcount ratio at national poverty lines (% of urban population), including noncomparable values                                                185
Survey mean consumption or income per capita, top 60% (2011 PPP $ per day)                                                                                     185
Multidimensional poverty, Sanitation (% of population deprived)                                                                                                185
Income share held by lowest 20%                                                                                                                                185
Income share held by fourth 20%                                                                                                                                185
Number of poor at $5.50 a day (2011 PPP) (millions)                                                                                                            185
Rural poverty headcount ratio at national poverty lines (% of rural population), including noncomparable values                                                185
Urban poverty gap at national poverty lines (%), including noncomparable values                                                                                185
Urban poverty headcount ratio at national poverty lines (% of urban population)                                                                                185
Poverty gap at $5.50 a day (2011 PPP) (% of population)                                                                                                        185
Income share held by second 20%                                                                                                                                185
Urban poverty gap at national poverty lines (%)                                                                                                                185
Rural poverty headcount ratio at national poverty lines (% of rural population)                                                                                185
Poverty gap at $3.20 a day (2011 PPP) (% of population)                                                                                                        185
Survey mean consumption or income per capita, top 10% (2011 PPP $ per day)                                                                                     185
Poverty headcount ratio at $1.90 a day, with secondary education (2011 PPP) (% of population age 16+ with secondary education)                                 185
Poverty headcount ratio at $1.90 a day, age 65+ (2011 PPP) (% of population age 65+)                                                                           185
Poverty headcount ratio at $1.90 a day, rural (2011 PPP) (% of rural population)                                                                               185
Name: Indicator Name, dtype: int64